---

- name: Include windows-common role
  include_role:
    name: windows-common

- name: Install python 2.7.13
  win_chocolatey:
    name: python2
    version: 2.7.13
    state: present

- name: Install feature Windows-Containers
  win_feature:
    name: 'Containers'
    state: present

- name: Install feature NET-Framework-Features
  win_feature:
    name: 'NET-Framework-Features'
    state: present

- name: Install feature Hyper-V
  win_feature:
    name: 'Hyper-V'
    include_management_tools: True
    state: present

- name: Install DockerProvider
  win_psmodule:
    name: DockerProvider

- name: Reboot the system
  win_reboot:
    test_command: powershell.exe 'Get-WindowsFeature'
    pre_reboot_delay: 15
    post_reboot_delay: 15
  tags:
    - skip_lint

- name: Wait for reconnection
  wait_for_connection:

- name: Install Docker-EE
  win_shell: "Install-Package Docker -ProviderName DockerProvider -Force"

- name: Pull docker images
  win_shell: "docker pull {{ item }}"
  with_items:
    - microsoft/nanoserver
    - microsoft/windowsservercore
    - python:3.6.5

- name: Install MS Visual C++ Redist 14
  win_chocolatey:
    name: vcredist140
    state: present

- name: Disable Windows Firewall
  win_firewall:
    profiles:
      - Domain
      - Private
    state: disabled

- name: Stop Docker
  win_service:
    name: docker
    state: stopped

- name: Remove container networks
  win_shell: |
    Get-NetNat | Remove-NetNat -Confirm:$false
    Get-ContainerNetwork | Remove-ContainerNetwork -Force

- name: Enable testsigning
  win_shell: |
    Bcdedit.exe -set TESTSIGNING ON
