pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Windows CI.
    failure-message: Build failed (check pipeline).
    success-message: Build succeeeded (check pipeline).
    footer-message: > 
                      This is a pipeline from Windows CI. For more information, see:
                      https://github.com/Juniper/contrail-windows-ci/wiki/OpenContrail-Windows-CI-FAQ
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
          branch:
            - ^master$
            - ^contrail/ocata$
            - ^contrail_dpdk_17_02$
            - ^contrail_dpdk_17_11$
            - ^R5\..*$
            - ^release-3.7-contrail$
            - ^release-3.9-contrail$
        - event: change-restored
          branch:
            - ^master$
            - ^contrail/ocata$
            - ^contrail_dpdk_17_02$
            - ^contrail_dpdk_17_11$
            - ^R5\..*$
            - ^release-3.7-contrail$
            - ^release-3.9-contrail$
        - event: comment-added
          branch:
            - ^master$
            - ^contrail/ocata$
            - ^contrail_dpdk_17_02$
            - ^contrail_dpdk_17_11$
            - ^R5\..*$
            - ^release-3.7-contrail$
            - ^release-3.9-contrail$
          comment: (?i)recheck(( (?:bug|lp)[\s#:]*(\d+))|( no bug))?(\s+clean)?\s*$
        - event: comment-added
          comment: (?i)recheck windows$
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: check-development
    description: Pipeline used for Windows CI development. It should always work in silent mode.
    manager: IndependentPipelineManager
    precedence: low
    trigger:
      gerrit:
        - event: patchset-created
          branch: ^master$
        - event: change-restored
          branch: ^master$
        - event: comment-added
          comment: (?i)recheck windows(?:-| )(dev|devel|development)\s*$

jobs:
  - name: ^ci-contrail-windows.*$
    success-pattern: &logs_url http://logs.opencontrail.org/winci/{build.uuid}/
    failure-pattern: *logs_url

project-templates:
  - name: ci-contrail-windows-template
    check:
      - ci-contrail-windows-production

  - name: ci-contrail-windows-other-projects-template
    check:
      - noop

projects:
  - name: Juniper/contrail-api-client
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-controller
    template:
      - name: ci-contrail-windows-template
    check-development:
      - ci-contrail-windows-development

  - name: Juniper/contrail-vrouter
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-build
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-third-party
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-common
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-windows-docker-driver
    template:
      - name: ci-contrail-windows-template

  - name: Juniper/contrail-windows
    template:
      - name: ci-contrail-windows-template
    check-development:
      - ci-contrail-windows-development

# AUTOMATICALLY GENERATED NOOPs BELOW - DO NOT MODIFY THESE LINES MANUALLY

  - name: Juniper/contrail
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-analytics
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-ansible
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-ansible-deployer
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-ansible-internal
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-ci-test
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-community-docs
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-container-builder
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-controller-test
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-dev-env
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-docker
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-docs
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-dpdk
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-fabric-utils
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-generateDS
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-heat
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-helm-deployer
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-horizon
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-java-api
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-kolla-ansible
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-neutron-plugin
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-nova-vif-driver
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-packages
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-packaging
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-project-config
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-provisioning
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-puppet
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-sandesh
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-server-manager
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-specs
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-test
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-test-ci
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-third-party-cache
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-third-party-packages
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-vcenter-manager
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-vcenter-plugin
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-vnc
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-vro-plugin
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-vrouter-java-api
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-web-controller
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-web-core
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-web-server-manager
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-web-storage
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-webui-third-party
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/contrail-zuul-jobs
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/horizon
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/nova
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/openshift-ansible
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/openstack-helm
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/openstack-helm-infra
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/puppet-contrail
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: Juniper/vijava
    template:
      - name: ci-contrail-windows-other-projects-template

  - name: tungstenfabric/contrail-ci-test
    template:
      - name: ci-contrail-windows-other-projects-template
