---

- name: Destroy VM '{{ inventory_hostname }}'
  delegate_to: localhost
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    folder: "{{ vcenter_datacenter }}/vm/{{ testenv_folder }}"
    name: "{{ inventory_hostname_short }}"
    state: absent
    force: yes
