---

- name: Get testbed VM facts from VMware
  delegate_to: localhost
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder: "{{ vcenter_datacenter }}/vm/{{ testenv_folder }}"
    name: "{{ inventory_hostname_short }}"
  register: newvm
  retries: 120
  delay: 60
  until: >
      newvm.instance.hw_eth0.ipaddresses | ipv4 | reject("match", "169.254.*") | list

- name: Set obtained IP as ansible_host
  set_fact:
    ansible_host: "{{ newvm.instance.hw_eth0.ipaddresses | ipv4 | first }}"

- name: Show obtained IP
  debug:
    var: ansible_host
