---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_prompt:
    - name: vm_role
      prompt: Provide 'vm_role'
      private: no
    - name: base_template
      prompt: Provide 'base_template'
      private: no
  tasks:
    - name: Preserve prompted parameters
      set_fact:
        vm_role: "{{ vm_role }}"
        base_template: "{{ base_template }}"

- hosts: localhost
  connection: local
  vars:
    template_folder: "Templates/CI"
  roles:
    - { role: vmware-template, stage: create }

- hosts: template
  gather_facts: no
  tasks:
    - name: Wait for new "{{ hostvars[localhost].vm_role }}" template to become reachable
      wait_for_connection:
        sleep: 5
        timeout: 900

- hosts: template
  gather_facts: no
  tasks:
    - name: Include "{{ hostvars[localhost].vm_role }}" role
      include_role:
        name: "{{ hostvars[localhost].vm_role }}"

- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - { role: vmware-template, stage: template }
