---
- hosts: localhost
  gather_facts: no
  connection: local
  vars_prompt:
  - name: testenv_name
    private: no
  - name: testenv_folder
    private: no
  - name: testenv_mgmt_network
    private: no
  - name: testenv_data_network
    private: no
  - name: testenv_controller_template
    private: no
  - name: testenv_testbed_template
    private: no
  - name: vcenter_datastore_cluster
    private: no
  tasks:
  - name: Preserve prompted parameters
    set_fact:
      testenv_name: "{{ testenv_name }}"
      testenv_folder: "{{ testenv_folder }}"
      testenv_mgmt_network: "{{ testenv_mgmt_network }}"
      testenv_data_network: "{{ testenv_data_network }}"
      testenv_controller_template: "{{ testenv_controller_template }}"
      testenv_testbed_template: "{{ testenv_testbed_template }}"
      vcenter_datastore_cluster: "{{ vcenter_datastore_cluster }}"

- hosts: localhost
  gather_facts: no
  connection: local
  roles:
  - testenv-inventory-build

- hosts: localhost
  connection: local
  tasks:
  - name: Create temporary directory for Python scripts
    tempfile:
      state: directory
    register: script_path
  - name: Copy scripts
    copy:
      src: "files/{{ item }}"
      dest: "{{ script_path.path }}"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: 0755
      force: yes
    with_items:
    - vmware_api.py
    - provision_vm.py

- hosts: testenv
  gather_facts: no
  any_errors_fatal: true
  tasks:
  - name: Add script_path to each host in testenv group
    delegate_to: localhost
    set_fact:
      script_path: "{{ hostvars['localhost'].script_path }}"

- hosts: testenv
  gather_facts: no
  any_errors_fatal: true
  roles:
  - role: vmware-vm
    action: deploy

- hosts: testenv
  gather_facts: no
  any_errors_fatal: true
  tasks:
  - name: "Wait for hosts in testenv to become reachable"
    wait_for_connection:
      sleep: 5
      timeout: 900

- hosts: controller
  roles:
    - controller

- hosts: localhost
  gather_facts: no
  connection: local
  roles:
    - testenv-save-conf
