---

- hosts: localhost
  roles:
    - { role: vmware-template, stage: create }

- hosts: "{{ vm_role }}"
  gather_facts: no
  tasks:
    - name: "Wait for new {{ vm_role }} template to become reachable"
      wait_for_connection:
        sleep: 5
        timeout: 1800

- hosts: "{{ vm_role }}"
  roles:
    - "{{ vm_role }}"

- hosts: localhost
  roles:
    - { role: vmware-template, stage: template }
